#!/bin/sh
#
# Usage: script/test
# Description: script to run test
#

set -e

# this script should be run in project root
BASE_DIRECTORY=`pwd`
RUBY_VERSION="2.1.5"
INFRATASTER_VERSION="0.2.2"

docker kill target > /dev/null 2>&1 || true
docker rm   target > /dev/null 2>&1 || true

# Test Ruby version
target_ruby_version=$(docker run --rm --name target target ruby -v | grep -e "^ruby $RUBY_VERSION" --line-buffered)

if [ "$target_ruby_version" == "" ]; then
  echo "Invalid Ruby version. expected: ${RUBY_VERSION}"
  exit 1
fi

# Test Infrataster version
target_infrataster_version=$(docker run --rm --name target target gem list infrataster | grep -e "^infrataster ($INFRATASTER_VERSION)$" --line-buffered)

if [ "$target_infrataster_version" == "" ]; then
  echo "Invalid Infrataster version. expected: ${INFRATASTER_VERSION}"
  exit 1
fi
