#!/bin/sh
#
# Usage: script/test
# Description: script to run test
#

set -e

# this script should be run in project root
BASE_DIRECTORY=`pwd`

echo "==> Building target..."
cd ${BASE_DIRECTORY}
docker build -t target .

echo "==> Running tester..."
script/run-tester

echo "==> Cleaning up..."
docker kill target > /dev/null 2>&1 || true
docker rm   target > /dev/null 2>&1 || true
